
name: Node Github CI

on:
  push:
    branches:
      - master

jobs:
  # TEST
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install and Test
      run: |
        npm install
        npm test
      env:
        CI: true
  
  # PRETTIER
  prettier:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2.1.2
    - name: Install and Prettier
      run: |
        npm install
        npm run prettier
      env:
        CI: true

  # BUILD
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2.1.2
    - name: Install and Build
      run: |
        npm install
        npm build
      env:
        CI: true