name: Publish to NPM

on: 
  workflow_dispatch:
    inputs:
      version:
        description: Release Type - patch | minor | major | 1.2.3
        default: patch
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2.1.2
      with:
        registry-url: 'https://registry.npmjs.org'
    - name: Install, Build and Publish
      run: |
        npm install
        npm run build
        npm whoami
        npx np ${{ github.event.inputs.version }}
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
